const express = require('express')
const userRouter = express.Router()
const {reg,login, getEmps, editTask, editStatus, editDetails, updStatus, updDetails, updTask, delUser, getEmpData, sendOtp, validateOtp, resetPwd} = require('../controllers/userController')
userRouter.post('/reg',reg)
userRouter.post('/login',login)
userRouter.get('/getallemps',getEmps)
userRouter.get('/edittask/:id',editTask)
userRouter.get('/editdetails/:id',editDetails)
userRouter.get('/editstatus/:id',editStatus)
userRouter.put('/updtask',updTask)
userRouter.put('/upddetails',updDetails)
userRouter.put('/updstatus',updStatus)
userRouter.delete('/deluser/:id',delUser)
userRouter.get('/gettasks/:id',getEmpData)
userRouter.get('/sendotp/:id',sendOtp)
userRouter.get('/validateotp/:id/:otp',validateOtp)
userRouter.put('/resetpwd',resetPwd)
module.exports = userRouter